### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LiamSirBean** [tomphttp/bare-server-node#18]
Does this need to be used with a proxy for example ultraviolet?

**Comment by Riftriot** [comment]
no

**Comment by IlanLuci** [comment]
Just run the .jar file

**Comment by LiamSirBean** [comment]
I have tried running it so when I click on a button that redirects to a new website it does it in its own proxy service

**Comment by LiamSirBean** [comment]
Didnt work for me

**Comment by e9x** [comment]
> Does this need to be used with a proxy for example ultraviolet?

The Bare server is independent of front end proxies. You can host the Bare server for fun, but ideally you would use it with a front end proxy like Ultraviolet.
