### ISSUE TITLE
How can I build a bare server like uv-node?

### ISSUE THREAD

**Issue by habataku** [tomphttp/bare-server-node#2]
Is there a way to build only bare-server without uv-static using heroku, Vercel, VPS server, etc.? Or are you planning to reflect the bare-server-v2 you are probably developing in uv or incognito?

**Comment by e9x** [comment]
As far as I'm aware, Ultraviolet is compatible with the official bare server protocol, and as such, this repository. We haven't created deploy scripts, but this can be looked into. You can run the bare server on any server by running the following:
```sh
git clone https://github.com/tomphttp/bare-server-node.git
cd bare-server-node
npm install
node ./app.js
```
