### ISSUE TITLE
Issue with ipaddr

### ISSUE THREAD

**Issue by VillainsRule** [tomphttp/bare-server-node#20]
The "ipaddr.js" dependency can crash the app.

The issue is, sometimes "string" is actually an array of objects. 
<img width="546" alt="Screen Shot 2023-05-22 at 5 50 51 PM" src="https://github.com/tomphttp/bare-server-node/assets/101288516/07e83ace-4101-4d08-a83b-9f41577415c3">

I've currently fixed it by adding the following line to the module:
```js
        if (typeof string === 'object') string = string[0].address;
```
However, I'm looking for a more permanent solution.
<img width="506" alt="Screen Shot 2023-05-22 at 5 53 35 PM" src="https://github.com/tomphttp/bare-server-node/assets/101288516/52a4106f-7857-4699-a206-d469f7d35f75">

Not sure if this is an installation error.
I'm using the latest version of this, and am using this package as it is required for Ultraviolet deployment.

**Comment by e9x** [comment]
fixed in 354e314521c56968b7d1ae8dcbd2454bc9912122
