### ISSUE TITLE
package-lock.json's "fedora:4873" messing up installation

### ISSUE THREAD

**Issue by binary-person** [tomphttp/bare-server-node#8]
attempting to run `npm install github:tomphttp/bare-server-node` causes an error because of local settings

```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://fedora:4873/yallist/-/yallist-4.0.0.tgz failed, reason: getaddrinfo ENOTFOUND fedora
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

my suggestion is deleting the package-lock.json file or npm installing it on a machine that doesn't have settings that don't work on another's

**Comment by e9x** [comment]
I was experimenting with my NPM registry and didn't realize I updated this repository's lockfile. This should be fixed in v1.0.3-deps2
