### ISSUE TITLE
IDK if this is the right place but

### ISSUE THREAD

**Issue by NVB9ALT** [tomphttp/bare-server-node#9]
I've been unable to use the chaoshistory.info proxy service for several days now because this keeps happening:
![Yxorp broken](https://user-images.githubusercontent.com/102188956/185759017-614f27cd-9704-4b0a-93aa-cefeefbf18f3.png)
Any help on this?

**Comment by e9x** [comment]
This isn't the right place, however I will look into it.

**Comment by e9x** [comment]
the problem was discovered and a fix is currently being deployed
